### PR TITLE
Issue#101 avmodel

### PR DESCRIPTION
**Pull request by yingfeng-iu**
Fixes #issuenumber ; refs #issuenumber

Present tense short summary (50 characters or less)

More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.

Description can have multiple paragraphs and you can use code examples inside:

``` ruby
class PostsController
  def index
    respond_with Post.limit(10)
  end
end
```

Changes proposed in this pull request:
*
*
*

@samvera-labs/avalon

### CODE REVIEW

**Comment by yingfeng-iu** [comment]
This hasn't been tested locally yet, and there're TODO items to review and confirm.

**Comment by jlhardes** [comment]
All of this is just for app/models/audiovisual_work.rb:

bibliographic_id - this is the web form field name so not sure if that is what it should be called in the .rb script; this field should map to owl:sameAs to store it as the identifier used for bib import; loc:local is only used for what has been <identifier@type=“other”> in MODS

oclc - dbpedia is not part of rdf-vocab gem yet but it does look like it’s part of QA Authorities: https://github.com/ld4l-labs/linked_data_authorities so the oclc property should be something we can call up?

title - Avalon doesn’t offer multiple titles where Hyrax does; I’m not sure why Hyrax facets on title, that’s not very useful and I wouldn’t recommend it

creator and contributor - we were recommending those map to dce:creator and dce:contributor because we thought that MARCRelators required URIs but we’ve since learned from LOC that they do not, so the properties you have for creator and contributor are fine

genre - I think all fields should be searchable so that would include genre

physical_description - the MODS and RDF subgroup has changed it’s mapping recommendation to move away from Bibframe (this original version is literally being removed from the web - I think that's a wrong approach but that’s what we hear they are planning to do); instead, we’re looking at this property for extent: http://www.rdaregistry.info/Elements/u/#P60550 (rdau:extent.en); It’s not likely available in rdf-vocab or QA Authorities but it’s a better property to use, esp. if Bibframe 1.0 goes away

related_item_url - dce:relation is used in default Hyrax for the Keywords field right now (which is not a great mapping) and there is no way to associate a label using this property. We are recommending using rdfs:seeAlso for the related item URL and rdfs:label for the related item label to keep them as simple properties and try to tie them together as properties on the work. Hyrax out of the box uses rdfs:seeAlso for it’s related item as well but doesn’t offer a label field.

permalink - should be dce:identifier; the permalink is the unique identifier of record for the Avalon item

terms_of_use - sure, this can searchable, I guess. If we have it searchable in Avalon now, keep it that way. If we don’t, then leave it as not searchable.

statement_of_responsibility - this is mapped correctly but it should be noted that the value is always going to need to begin with “Statement of Responsibility: “ followed by the entered text. That is the only way we’re going to tell the difference between multiple SKOS.notes.

note_type - this is not actually a property in the AV work type; there is only the property “:note” that maps to ::RDF::Vocab::SKOS.note. We’ll have a drop-down of note type options (like we do now) and those become the beginning of the text value for the :note property, just like statement_of_responsibility.

**Comment by cjcolvar** [comment]
Fixes #101.

**Comment by jlhardes** [comment]
I think there might be a couple things missing, but I'm not sure. I don't see permalink anywhere but is that because we're using dct:identifier which is part of Hyrax default metadata? I also don't see statement of responsibility anywhere either although the skos:note field for note might be where that will live so it doesn't have to be distinctly defined in these changes.

These changes are reflecting that we're using Hyrax fields as they are defined by default for title, creator, contributor, publisher, date created, language, and terms of use (so they aren't specifically listed in these changes but come in with the Hyrax basic and core metadata code). This also might be reflecting that we're using dct:identifier from Hyrax for our permalink field, but I want to verify that. 

It occurs to me that we can also use the Hyrax default field for topical subject - dce:subject. That might be worth a change to remove that from the AudiovisualWork definition.

**Comment by cjcolvar** [comment]
@jlhardes I think I addressed your questions with that last commit.  I removed topical_subject in favor of Hyrax's subject and added comments for fields that we're getting from Hyrax.

**Comment by jenyoung** [comment]
@jlhardes and I discussed and are good to go.

**Comment by jlhardes** [comment]
Dates are still concern but @jenyoung and I are ok with this for now. Might need to change later to use only date_created but not sure how migration path could work for folks already using Avalon.

We are good to go from a metadata viewpoint for this first iteration!

**Comment by jenyoung** [comment]
@jlhardes and I discussed. We are good to go.

**Pull request merged**
