### PR TITLE
Dynamically paginate encode index page

### PR DESCRIPTION
**Pull request by bkeese**
Initialize datatable in transcode index page to use ajax to retrieve paginated, sorted, and filtered results.

@samvera-labs/avalon

### CODE REVIEW

**Comment by bkeese** [comment]
The problem is that the values we store in the DB are not the values we are sorting/filtering on.

**Comment by cjcolvar** [comment]
If that's the case then maybe we should add columns to the encode record DB table.

**Comment by bkeese** [comment]
That would vastly simplify things.

**Comment by cjcolvar** [comment]
I'm overlooking the rubocop exceptions since we're planning on moving this code to `hyrax-active_encode` soon and it doesn't really make sense to add the exception to then have to remove it when the file disappears.

**Pull request merged**
